<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="vista/assets\css\bootstrap.min.css">

	<link rel="stylesheet" href="vista/assets/css/style.css">
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/
font-awesome/4.7.0/css/font-awesome.min.css">
		
<link rel="stylesheet" type="text/css" href="vista/assets/DataTables/datatables.min.css"/>

</head>



<body class="bg">



<script src="vista/assets/js/jquery.js"></script>
<script src="vista/assets/js/funciones.js"></script>

<script src="vista\assets\js\popper.js"></script>
<script src="vista\assets\js\bootstrap.min.js">"></script>

<script type="text/javascript" src="vista/assets/DataTables/datatables.min.js"></script>



</body>
</html>