
<?php
session_start();


?>


<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

	<link rel="stylesheet" href="assets/css/style.css">
	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/
font-awesome/4.7.0/css/font-awesome.min.css">
		
<link rel="stylesheet" type="text/css" href="assets/DataTables/datatables.css"/>
<style type="text/css">
	.nav-tabs .nav-link.active{
	    background-color: #007bff!important;
	    color: white!important;
	}

	.dataTables_length, .dataTables_filter{
		padding-bottom: 1rem!important;
		padding-top: 1rem!important;
	}
</style>
</head>



<body class="bg">


<section class="footer row card-footer text-light">
	<div class="col">
	   <div class=" text-ligt naranja ">
    						SENA CTMA 2020 TODOS LOS DERECHOS RESERVADOS.
  					</div>
	</div>

		<div class="col">
					
		</div>

		<div class="col text-right ">
			<img  src="assets\images\logosena.svg" alt="logo sena" width="30px" height="30px">
		</div>
</section>


<script src="assets/js/jquery.js"></script>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- <script type="text/javascript" src="assets/DataTables/datatables.min.js"></script> !-->
<script type="text/javascript" src="assets/DataTables/datatables.js"></script>

<script src="assets/js/funciones.js"></script>
</body>
</html>