<?php  
include('cabeza.inc');
?>

<div class="pos-f-t">
<div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bgverdea p-4">
      <h4 class="text-white">Collapsed content</h4>
      <span class="text-muted">Toggleable via the navbar brand.</span>
    </div>
  </div>
  <nav class="navbar navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
</div>
</div>



<footer class="page-footer font-small   footer  ">


	<div id="footer" class="container-fluid text-center text-md-left">


		<div class="row ">


			<div class="col-md-6 mt-md-0 ">


				<h6 class="text-uppercase text-center font-weight-bold text-light ">Aviso</h6>
				<p class="font-weight-bold">
					recuerde que su usuario es el correo @misena y su contraseña es el documento con el cual está registrado en la institucion
				</p>

			</div>





			<div class="col-md-6 mb-md-0 mb-3">


				<h6 class="text-uppercase font-weight-bold text-light text-center">¡Recuerda!</h6>
				<p class="font-weight-bold">Solo puedes tener un perfil activo en caso de tener mas de 1,
					si tienes problemas para visualiar tu horario debes filtrar los resultados ,
					así la visualizacion es mas fácil.</p>

			</div>


		</div>


	</div>

</footer>
